name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.6
  PROJECT_NAME: PsychEngine

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        if: inputs.name != 'Linux ARM64'
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Setup Haxe (Linux ARM64 Workaround)
        if: inputs.name == 'Linux ARM64'
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt install haxe -y
          haxelib setup ~/haxelib

      - name: Setup MSVC ARM64
        if: inputs.name == 'Windows ARM64'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: amd64_arm64

      - name: Install libVLC
        if: contains(inputs.name, 'Linux')
        run: sudo apt install libvlc-dev libvlccore-dev

      - name: Setup Android NDK
        if: inputs.name == 'Android'
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r29-beta1
          add-to-path: false

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp.git
          haxelib git lime https://github.com/mcagabe19-stuff/lime-8.2.0
          haxelib install openfl
          haxelib install flixel 5.8.0
          haxelib install flixel-tools
          haxelib install flixel-ui 2.6.1
          haxelib install flixel-addons 3.2.2
          haxelib install tjson
          haxelib install hxcpp https://github.com/MobilePorting/hxcpp
          haxelib install hxCodec https://github.com/MobilePorting/hxCodec
          haxelib install hxvlc 1.7.1
          haxelib install hxjsonast
          haxelib install SScript https://github.com/MobilePorting/SScript-7.7.0
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit-rewriten
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate.git
          haxelib install compiletime
          haxelib install flixel-screenshot-plugin

      - name: Configure Android
        if: inputs.name == 'Android'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
          haxelib set flixel-addons 3.2.2
          haxelib set hxvlc 1.7.1

      - name: Compile
        run: haxelib run lime build ${{ inputs.buildArgs }}

      - name: Make IPA
        if: inputs.name == 'iOS'
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r ${{ env.PROJECT_NAME }}.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error
